name = "astrodx-wiki"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-12-11"

[placement]
mode = "off"

[env.production]
compatibility_flags = ["nodejs_compat"]
vars = { NODE_VERSION = "22.12.0" }

[env.production.placement]
mode = "smart"